name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Github-Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true

      - name: Deploy to Server
        run: |
          ftp -n <<EOF
          ${{ secrets.FTP_LOGIN_COMMAND }}
          prompt
          lcd dist
          mput *
          EOF
